CREATE TABLE [dbo].[Game]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
	[Started] BIT NOT NULL DEFAULT 0,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[HostId] INT NOT NULL,
	CONSTRAINT [FK_Game_User] FOREIGN KEY (HostId) REFERENCES [dbo].[User](Id)
)
